version: "3.5"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
    - pgdata:/var/lib/postgresql/data/

  pg4:
    container_name: pg4
    image: thajeztah/pgadmin4
    ports:
      - 5050:5050

volumes:
  pgdata:
