version: "3.5"

services:
  db1:
    container_name: db1
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env

  pg41:
    container_name: pg41
    image: thajeztah/pgadmin4
    ports:
      - 5050:5050


